# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

import pandas as pd
import numpy as np 

#from google.colab import drive
#drive.mount('/content/gdrive')

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [4]:
import os
from sklearn.datasets import load_iris 
from sklearn.model_selection import train_test_split

!pwd
#root_path = '/gdrive/My Drive/Colab Notebooks/GL AIML Lab & Project' 
#os.chdir(root_path)

#iris_df = pd.read_csv("iris.csv")

iris_dataset = load_iris()

/content


## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [5]:
#tf.data.Dataset.from_tensors(iris_df)
#iris_features = pd.DataFrame(iris_dataset.data)
#iris_target = pd.DataFrame(iris_dataset.target)

iris_features = iris_dataset.data
iris_target = iris_dataset.target

print(np.shape(iris_features))
print(np.shape(iris_target))

print(type(iris_features))
print(type(iris_target))

(150, 4)
(150,)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [6]:
X_train, X_test , y_train , y_test =  train_test_split(iris_features, iris_target , test_size = 0.25 , random_state = 1 )

print(np.shape(X_train))
print(np.shape(y_train))
print(np.shape(X_test))
print(np.shape(y_test))

print(type(iris_features))
print(type(iris_target))
print(type(X_train))
print(type(y_train))

(112, 4)
(112,)
(38, 4)
(38,)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [7]:
from keras.utils import to_categorical
#print(iris_target)
y_train = to_categorical(y_train, num_classes = 3 )
y_test = to_categorical(y_test, num_classes = 3 )

#print(y_train)
#print(y_test)

Using TensorFlow backend.


## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from keras.models import Sequential
from tensorflow.keras import layers

seq_keras_model = tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [9]:
from tensorflow.keras.layers import Dense

input_shape = X_train[0].shape
print(input_shape)
#Input Layer
seq_keras_model.add(Dense(units=10, activation='relu',input_shape= input_shape))

#Hiddel Layer 1 
seq_keras_model.add(Dense(units=8, activation='relu'))

#Hiddel Layer 2 
seq_keras_model.add(Dense(units=5, activation='relu')) 

#Output Layer
seq_keras_model.add(Dense(units=3, activation='softmax'))

(4,)


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
from keras import optimizers

seq_keras_model.compile(loss='categorical_crossentropy', metrics=['accuracy'] , optimizer='SGD')

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [11]:
seq_keras_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 45        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 18        
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [12]:
print(np.shape(X_train))
print(np.shape(y_train))
print(np.shape(X_test))
print(np.shape(y_test))

seq_keras_model.fit(x = X_train, y= y_train , epochs=300 , batch_size=100, verbose = 1,  validation_data=(X_test,y_test))

#y_train 
#X_train

(112, 4)
(112, 3)
(38, 4)
(38, 3)
Train on 112 samples, validate on 38 samples
Epoch 1/300
112/112 [==============================] - 1s 6ms/sample - loss: 1.2234 - accuracy: 0.3304 - val_loss: 1.1955 - val_accuracy: 0.3421
Epoch 2/300
112/112 [==============================] - 0s 147us/sample - loss: 1.1443 - accuracy: 0.3304 - val_loss: 1.1478 - val_accuracy: 0.3421
Epoch 3/300
112/112 [==============================] - 0s 176us/sample - loss: 1.1007 - accuracy: 0.3304 - val_loss: 1.1077 - val_accuracy: 0.3421
Epoch 4/300
112/112 [==============================] - 0s 139us/sample - loss: 1.0642 - accuracy: 0.3304 - val_loss: 1.0791 - val_accuracy: 0.3421
Epoch 5/300
112/112 [==============================] - 0s 127us/sample - loss: 1.0395 - accuracy: 0.3304 - val_loss: 1.0501 - val_accuracy: 0.3421
Epoch 6/300
112/112 [==============================] - 0s 144us/sample - loss: 1.0166 - accuracy: 0.3304 - val_loss: 1.0305 - val_accuracy: 0.3421
Epoch 7/300
112/112 [====================

## Question 10

### Make predictions
- Predict labels on one row

In [13]:
loss_and_metrics = seq_keras_model.evaluate(X_test, y_test, batch_size=128)

38/38 [==============================] - 0s 98us/sample - loss: 0.2313 - accuracy: 0.9737


In [0]:

seq_keras_model_predict = seq_keras_model.predict(X_test, batch_size=None, verbose=0, steps=None, callbacks=None, max_queue_size=10, workers=1, use_multiprocessing=False)
#seq_keras_model.metrics

seq_keras_model_predict = np.round(seq_keras_model_predict,0)

In [15]:
score, acc = seq_keras_model.evaluate(X_test, y_test)
print(score)
print(acc)

38/38 [==============================] - 0s 230us/sample - loss: 0.2313 - accuracy: 0.9737
0.23129455745220184
0.9736842


### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [0]:
#seq_keras_model.predict_proba(X_test)

In [17]:
from sklearn.metrics import accuracy_score
print(np.shape(y_test))
print(np.shape(seq_keras_model_predict))

print(y_test)
print(seq_keras_model_predict)


(38, 3)
(38, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]




---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [19]:
import tensorflow as tf
import numpy as np
import pandas as pd
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [21]:
# run this cell to upload file if you are using google colab
#from google.colab import files
#files.upload()

from google.colab import drive
drive.mount('/content/gdrive')


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [22]:
!pwd
#!cd('/content/gdrive/My Drive/')
#root_path = '/gdrive/My Drive/Colab Notebooks/GL AIML Lab & Project' 
!pwd

/content
/content


In [23]:
FilePath = "/content/gdrive/My Drive/prices.csv"
prices_df = pd.read_csv(FilePath)
print(type(prices_df))
print(prices_df.shape)

<class 'pandas.core.frame.DataFrame'>
(851264, 7)


## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
prices_df.drop(columns = ['date','symbol'],inplace = True)

In [25]:
prices_df.shape
prices_df.head(5)

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [26]:
prices_df_trunc = prices_df.head(1000)
print(prices_df_trunc.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
open      1000 non-null float64
close     1000 non-null float64
low       1000 non-null float64
high      1000 non-null float64
volume    1000 non-null float64
dtypes: float64(5)
memory usage: 39.2 KB
None


## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
y = prices_df_trunc["volume"]
X = prices_df_trunc.drop(columns = ["volume"])



## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
X_np = X.to_numpy(dtype = "float32")
y_np = y.to_numpy(dtype = "float32")

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
import tensorflow as tf

X_np = tf.math.l2_normalize(X_np,axis=None,epsilon=1e-12,name=None)



## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [30]:
wt = tf.zeros(shape = (4,1),dtype = tf.float32,name = "weights")
bias = tf.zeros(shape = (1),dtype = tf.float32, name ="bias")

print(wt)
print(bias)

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]], shape=(4, 1), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)


## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function
def pred(features, weight , bias):
  print('Inside Pred fn - Features shape is ' , features.shape)
  print('Inside Pred fn - Weights shape is ', weight.shape)
  #prediction = (features * weight) + bias

  prediction = tf.add(tf.matmul(features, weight),bias)
  print('Prediction is ' , prediction)
  return prediction


### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function
def loss_cal(actuals , predicted):
  diff = actuals - predicted
  mse = tf.reduce_mean(tf.square(diff))
  print('MSE is ' , mse)
  return mse


## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
@tf.function
def nn_train(data , target , weight , bias , learning_rate):
  
  # Recording operations on tape when calculating loss and prediction
  with tf.GradientTape() as t:
    t.watch([weight,bias])
    prediction = pred(data, weight , bias)
    loss = loss_cal(target , prediction)
  
  # Calculate gradients for loss with respect to weights and bias.
  dw , db = t.gradient(loss,[weight ,bias])
  
  print('Inside train fn - dw shape -> ' , np.shape(dw))
  print('Inside train fn - db shape -> ' ,np.shape(db))
  print(np.shape(learning_rate))

  # update weights and bias
  #weight = tf.subtract(weight,tf.matmul(learning_rate,dw))
  #bias = tf.subtract(bias, tf.matmul(learning_rate,db))

  #weight = tf.matmul(tf.subtract(weight,learning_rate),dw)
  #bias = tf.matmul(tf.subtract(bias, learning_rate),db)
  
  weight = weight - learning_rate * dw
  bias = bias - learning_rate * db

  return weight, bias




## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [37]:

print(np.shape(X_np))
print(np.shape(y_np))

for i in range(100):
  weight , bias = nn_train(X_np , y_np , wt , bias , 0.05)
  print("Training loss on iteration " , i ," is " , loss_cal(y_np , pred(X_np , wt , bias)).numpy())

(1000, 4)
(1000,)
Training loss on iteration  0  is  209045770000000.0
Training loss on iteration  1  is  209045760000000.0
Training loss on iteration  2  is  209045770000000.0
Training loss on iteration  3  is  209045770000000.0
Training loss on iteration  4  is  209045770000000.0
Training loss on iteration  5  is  209045770000000.0
Training loss on iteration  6  is  209045770000000.0
Training loss on iteration  7  is  209045770000000.0
Training loss on iteration  8  is  209045770000000.0
Training loss on iteration  9  is  209045770000000.0
Training loss on iteration  10  is  209045770000000.0
Training loss on iteration  11  is  209045770000000.0
Training loss on iteration  12  is  209045760000000.0
Training loss on iteration  13  is  209045770000000.0
Training loss on iteration  14  is  209045770000000.0
Training loss on iteration  15  is  209045770000000.0
Training loss on iteration  16  is  209045770000000.0
Training loss on iteration  17  is  209045760000000.0
Training loss on ite

### Observe values of Weight
- Print the updated values

In [38]:
print(weight)

tf.Tensor(
[[0.00284536]
 [0.00285051]
 [0.00281652]
 [0.00287384]], shape=(4, 1), dtype=float32)


### Observe values of Bias
- Print the updated values

In [40]:
print(bias)

tf.Tensor([5314219.5], shape=(1,), dtype=float32)
